### ISSUE TITLE
npm i uws failed

### ISSUE THREAD

**Issue by dotbloup** [uWebSockets/website#5]
I use node 10, npm 5.6.0 and npm i uws does not work. I get the following error in build_log.txt inside node_modules/uws 
Please find the file attached to this issue.
[build_log.txt](https://github.com/uWebSockets/website/files/1982515/build_log.txt)

> make: *** [Release/obj.target/uws/src/addon.o] Error 1
> make: Leaving directory `/root/seoserverdev2/node_modules/uws/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
> gyp ERR! System Linux 3.10.0-514.el7.x86_64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/seoserverdev2/node_modules/uws
> gyp ERR! node -v v10.0.0
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok

**Comment by thejerrytan** [comment]
hi i also have the same problem, on Mac High Sierra 10.13.6, node v10.0.0, npm v6.4.1, node-gyp v3.6.2

running node-gyp rebuild in the uws node_modules fails when compiling addon.o

Pls advice! Thanks!
